### ISSUE TITLE
Checklist - Research Related

### ISSUE THREAD

**Issue by rashmisangwan** [software-engineering-for-life/journey-to-be-a-better-software-engineer#5]
------------

 - [ ] Talking to teacher
 - [ ] R&D Big Data - Read few research papers
 - [ ] Call training Institute regarding Big Data @ankushjamdagani
