### ISSUE TITLE
Checklist - Learning React

### ISSUE THREAD

**Issue by rashmisangwan** [software-engineering-for-life/journey-to-be-a-better-software-engineer#7]
* [ ] Testing Frameworks Comparison  [Mocha + Karma + React.TestUtils (Chai | Sinon | fetch-mock | ...)]
  * [ ] Core ReactJS
    * [ ] Setup & Dev Environment
    * [ ] Webpack
    * [ ] Core ReactJS
    * [ ] CORS Error Handling
    * [ ] Redux
    * [ ] Caching & Logging
  * [ ] Projects
    * [ ] Gymday POS Assignment
    *  [ ] Personal Portfolio
    * [ ] Periodic Table App
    * [ ] Personal Cloud Simulation
      * [ ] Tasks and Data Management
      * [ ] SCRUM Implemented
      * [ ] R&D Documentation [PUBLIC | PRIVATE]
